### ISSUE TITLE
19 e 20 - .Net Framework / .Net Core

### ISSUE THREAD

**Issue by andrelugomes** [opensanca/podcast#22]

**Comment by LeonardoFerreiraa** [comment]
pt1: https://anchor.fm/opensanca/episodes/19----Net-framework-e--Net-Core-pt-12-ej1mgt/a-a33vngu
pt2: https://anchor.fm/opensanca/episodes/20----Net-framework-e--Net-Core-pt-22-ekgj5u/a-a3dvr43
