### ISSUE TITLE
26 - Programação reativa e Sistemas reativos

### ISSUE THREAD

**Issue by ederfmatos-exacta** [opensanca/podcast#23]
## Agenda

Apresentação dos convidados

Diferença entre Programação Reativa e Sistema Reativo.

O que é um sistema reativo? (a ideia é falar sobre o manifesto reativo) https://www.reactivemanifesto.org/
 - Que problema resolve
 - EDA é um tipo de implementação?

O que é Programação reativa?
 - Que problema resolve
 - Spec: https://www.reactive-streams.org/
 - Observer pattern
 - Reactor pattern - Event Driven

Diferença reatividade e assincronidade

Como muda o jeito de desenvolver quando tem que pensar em reativo?

publishers cold vs publishers hot (talvez esse seja mt nivel de código e não teorico)

"se não tem thread pool como funciona?" (a ideia é chegar num epoll da vida https://man7.org/linux/man-pages/man7/epoll.7.html)
- Thread
- courotines
- Event Loop

frameworks e bibliotecas
- Akka ?
- Akka Streams
- webflux
- Vert.x
- RXJava
- Kafka Streams ?
- Spring Cloud Stream?

Participantes:
https://www.linkedin.com/in/alexfgarcia/
https://www.linkedin.com/in/leonardoferreiraa/
https://www.linkedin.com/in/oriol-canalias/
https://www.linkedin.com/in/andreluisgomes/

**Comment by andrelugomes** [comment]
massa
