### ISSUE TITLE
Começo e evolução da carreira de um dev

### ISSUE THREAD

**Issue by daviguelfi** [opensanca/podcast#26]
## A ideia é tentar trazer de forma simples o começo da carreira e tentar retratar para quem está começando

+ Alguém do RH

# pauta

- Por que TI?
- - Grana
- - Propósito
- Faculdade e/ou Cursos
- Estágio/Dev Jr./Freelancer/Empreendedor primeiro?
- Seguir influencer?
- Como foi o começo de carreira de cada um?
- Mercado de hoje

- Carreiras para seguir

## Técnica
- -Front
-- Back
-- Mobile
-- Engenharia de Dados - BI
-- Operações - DevOps - SysAdmins
-- Administradores de sistemas - Redes...
-- Segurança - AppSec

## Gestão
-- Scrum Master / Agile master / Agilista
-- Gerente de Engenharia

## Produto
-- PO
-- PM
-- Designers

**Comment by andrelugomes** [comment]
massa

**Comment by marcel0ll** [comment]
Bem massa. Não sei se cabe na pauta, e também é algo menos comum, mas talvez seja interessante sobre a possibilidade de carreira como freelancer.

**Comment by andrelugomes** [comment]
> Bem massa. Não sei se cabe na pauta, e também é algo menos comum, mas talvez seja interessante sobre a possibilidade de carreira como freelancer.

acho que cabe sim

**Comment by daviguelfi** [comment]
Ansioso
