### ISSUE TITLE
22 - Zettelkasten - Como Tomar Notas e Organizar Conhecimento

### ISSUE THREAD

**Issue by andrelugomes** [opensanca/podcast#29]
Conversa sobre Como Tomar Notas

https://www.youtube.com/watch?v=K6SfmJIhShg

+ Rafa Girolinetto
+ Oriol
+ Cadu
+ Mendes

# Pauta

- Por que tomar notas é tão importante?

- Sistemas de Captura e Retenção de Conhecimento.

- Técnicas de Tomar notas e organização:

+ Second Brain
     + Tiago Forte
     + https://www.buildingasecondbrain.com/
+ Zettelkasten
     + Niklas Luhmann 
     + https://en.wikipedia.org/wiki/Zettelkasten
     + https://zettelkasten.de/introduction/
+ GTD
     + David Allen
     + https://gettingthingsdone.com/
     + Já gravamos um podcast com o Pothix sobre GTD
     + Book: Getting Things Done
+ ZTD
    + Leo Babauta
    + https://zenhabits.net/zen-to-done-the-simple-productivity-e-book/
    + Book: Zen to Done: The Ultimate Simple Productivity System
+ Outras

- Ferramentas

+ Notion
+ Trello
+ Markdown

**Comment by LeonardoFerreiraa** [comment]
https://anchor.fm/opensanca/episodes/22---Zettelkasten-Como-Tomar-Notas-e-Organizar-Conhecimento-en76p2
