### ISSUE TITLE
24 - Fullstack QA

### ISSUE THREAD

**Issue by andrelugomes** [opensanca/podcast#31]
Apresentação dos convidados
Diferença entre testes automatizados e testes manuais
Tipo de testes automatizados: piramide de testes
- Unitários
- Integrados
- End-to-End
Como encaixam os testes de Mobile?
Quando rodar os testes?
Quem é o responsável para desenvolver os testes?
Ferramentas que vocês usam diariamente?
Como evoluiu o papel do QA/Analista de qualidade? Fabrica de testes, qa no time, etc
Como vocês acham que vai evoluir este papel?
Diversidade: Porque temos tendência a associar o papel de QA à mulher?
Coisas que podemos colocar durante a conversa:
TDD afeta ao papel do QA? Vocês já viram usar no dia a dia?
E o BDD? Muitas vezes é relacionado à cucumber. Tem alguma coisa ver com testes?

**Comment by omegamendes** [comment]
Utilização de BDD em sistemas/ambientes que passam por muita mudança, é um problema dar manutenção nesses testes depois ou ainda apresenta um ganho que vale a pena sua implementação?

**Comment by andrelugomes** [comment]
> Utilização de BDD em sistemas/ambientes que passam por muita mudança, é um problema dar manutenção nesses testes depois ou ainda apresenta um ganho que vale a pena sua implementação?

bom ponto
