### ISSUE TITLE
OpenTelemetry

### ISSUE THREAD

**Issue by andrelugomes** [opensanca/podcast#34]
## Description

Houve release do LTS mes de fev/21

## Agenda

+ Divulgar link de Sugestões
+ Hosts
+ Guests

+ História
- https://opentracing.io/
- https://opencensus.io/

Dapper = https://research.google/pubs/pub36356/

https://zipkin.io/
https://www.jaegertracing.io/docs/1.22/ [Uber]

+ O que é o projeto?
 - https://opentelemetry.io/
 
 - https://opentelemetry.io/docs/concepts/what-is-opentelemetry/
 OpenTelemetry is a set of APIs, SDKs, tooling and integrations that are designed for the creation and management of telemetry data such as traces, metrics, and logs. The project provides a vendor-agnostic implementation that can be configured to send telemetry data to the backend(s) of your choice. It supports a variety of popular open-source projects including Jaeger and Prometheus.

+ Que problema resolve? Observabilidade?

 telemetry data such as traces, metrics, and logs.

+ Especificações

+ SDKs e Exporters

+ Divulgar link de Sugestões
- https://medium.com/opensanca/opensanca-podcast-4717f4e35322
- https://github.com/opensanca/podcast/issues

Imagem Ilustrativa
+ https://miro.medium.com/max/1080/1*Yu0bCux_sulHPy6MhT9Ytg.png

Vagas magnets
+https://jobs.kenoby.com/magnetis/job/pessoa-desenvolvedora-backend-elixir/605e244a7fe2e26df9603fbb

## Guest suggestions

+ Guga - Slack opensanca

**Comment by duduribeiro** [comment]
Publicado https://anchor.fm/opensanca/episodes/27---OpenTelemetry-evuurs
