### ISSUE TITLE
RabbitMQ

### ISSUE THREAD

**Issue by oriol-canalias-movile** [opensanca/podcast#44]
## Description
Vamos aprofundar (um pouco) em RabbitMQ

## Agenda

+ Advertisement / Annunciations
+ Hosts
+ Guests
Julio Falbo

### Sugestão de pauta
- O que é Rabbit
- só AMQP?
- Como envio uma mensagem?
- tipos de exchange, para que usar cada um
- Filas: Configurações básicas (Lazy, profundidade, DLQ)
- DLQ: O que é, para que serve
- Filas: Configurações avançadas (TTL, TTL da mensagem)
- Delay Queue: O que é (Estrategias de retry?)
- Virtualhosts
- Clusters e estratégias de ha

## Guest suggestions

+
+
+

**Comment by juliofalbo** [comment]
Guest suggestions
- Plugins
- Management UI
