### ISSUE TITLE
Go lang

### ISSUE THREAD

**Issue by iundarigun** [opensanca/podcast#47]
## Description
Vamos bater um papo sobre Go Lang

## Agenda
- Origem da linguagem
- Caraterísticas destacáveis
- Frameworks
- Testes
- Como é o deploy
- Migração vindo de outras linguagens
- performance
- como começar

## Hosts
- André Gomes
- Cadu Ribeiro
- Uri Canalias
- Rodrigo da arquivei

## Guests
- André Ribeirão : https://www.linkedin.com/in/ribeirao/
- Rodrigo Fonseca da arquivei : https://www.linkedin.com/in/rjfonseca/

lINKS:

https://golang.org/
https://talks.golang.org/2013/bestpractices.slide#1
https://golang.org/doc/effective_go
https://medium.com/wesionary-team/know-about-25-keywords-in-go-eca109855d4d
https://tour.golang.org/welcome/1

Vagas:
https://boards.greenhouse.io/raininstantpay

 https://arquivei.applytojob.com/apply/19ObAwSkRp/Engenheiro-De-Software-Junior

**Comment by rjfonseca** [comment]
Opa, Aqui é o Rodrigo da Arquivei. Esse aqui é o meu usuário do githuib.

**Comment by iundarigun** [comment]
Boa Rodrigo! Da uma olhada na pauta, aqui ninguém manja de Go 😂

**Comment by andrelugomes** [comment]
https://craig.horse/?id=96942208&key=263090416

**Comment by andrelugomes** [comment]
https://anchor.fm/opensanca/episodes/31---Go-e16ncmr
