### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by andrelugomes** [opensanca/podcast#54]
## Agenda

+ Advertisement / Annunciations
+ Hosts (André, Cris)
+ Guests
+ Um pouco da história do JavaScript
+ O que é ECMA Script?
+ Quem mantem o JavaScript?
+ Browsers e suporte
+ A gente programa em JavaScript como nos anos 2000 ainda? Apenas como Script de Suporte em HTML
+ Quando o JavaScript se modernizou?
+ Gerenciamento de Dependências

+ NodeJS
+ que problema ele resolveu?
+ contexto que surgiu?

## Guest suggestions

+
+
+

**Comment by cristofer-sousa-movile** [comment]
Falei com o Cabrini se ele tinha interesse em participar acho que faz sentido dado o movimento dele com JS. 
E vou falar com o Branas para ver se conseguimos isso.

Tem ideia de uma data para esse podcast para alinhar com eles?

**Comment by cristofer-sousa-movile** [comment]
@andrelugomes  consegui os palestrantes para próxima semana, Vedovelli não conseguirá para agora faremos uma outra rodada com ele a respeito de frameworks front-end,  veja se precisa de mais alguma info:


Podcast :  
Data:  09/03
Horário: 20:30

Palestrantes:  
- [william-bruno] (https://www.linkedin.com/in/wbrunom/) 
- [rodrigro-branas] (https://br.linkedin.com/in/rodrigobranas)

**Comment by cristofer-sousa-movile** [comment]
Link enviado e confirmado com os convidados.
